name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rental_demo_development
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.10'

      - name: Check Ruby version
        run: ruby -v

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bin/rails test